default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: film_sonar_development

test:
  <<: *default
  database: film_sonar_test

production:
  <<: *default # Hereda adapter, encoding, pool
  # Usa la URL proporcionada por el entorno de hosting
  url: <%= ENV['DATABASE_URL'] %>